services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nba_data
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      EXECUTOR: Local
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://developer:1234@postgres/nba_data
    volumes:
      - airflow-logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && airflow users create --username developer --password 1234 --firstname Airflow --lastname User --role Admin --email developer@example.com && airflow webserver"

  flaskapp:
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres-db-volume:
  airflow-logs: