services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nba_data
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg://airflow:airflow@postgres/airflow
    volumes:
      - airflow-logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver
  
  flaskapp:
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  
volumes:
  postgres-db-volume:
  airflow-logs:
  minio-data-volume: